name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Clean and install dependencies
      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          npm install
        env:
          NODE_ENV: development

      # Step 4: Debug workspace files
      - name: Debug: List workspace files
        run: ls -la

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Upload build artifacts
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Download build artifacts
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
