name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  CI: false
  NODE_OPTIONS: --openssl-legacy-provider # Add this to fix the OpenSSL issue

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci 
        
      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build

      - name: Check directory after downloading
        run: ls -la ./build  # Verify that the artifact has been downloaded correctly
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.TOKEN }}
            publish_dir: ./build